export const VIEW_CREATE_SESSION = "CREATE_SESSION";
export const VIEW_SESSION_MONITORING = "SESSION_MONITORING";
export const VIEW_MEDIA_ACCESS = "VIEW_MEDIA_ACCESS";
export const DEVICE_MEDIA_ACCESS_ACCEPTED = "DEVICE_MEDIA_ACCESS";
export const DEVICE_MEDIA_ACCESS_REQUESTED = "DEVICE_MEDIA_ACCESS_REQUESTED";
export const DEVICE_MEDIA_ACCESS_DECLINED = "DEVICE_MEDIA_ACCESS_DECLINED";

export type ViewType = typeof VIEW_CREATE_SESSION | typeof VIEW_SESSION_MONITORING | typeof VIEW_MEDIA_ACCESS;