export const VIEW_CREATE_SESSION = "CREATE_SESSION";
export const VIEW_SESSION_MONITORING = "SESSION_MONITORING";
export const VIEW_DATA_RECORDING = "VIEW_DATA_RECORDING";

export type ViewType = typeof VIEW_CREATE_SESSION | typeof VIEW_SESSION_MONITORING | typeof VIEW_DATA_RECORDING;