version: "3"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=bubu
      - MYSQL_DATABASE=licenta
    ports:
      - 3306:3306
  mail:
    image: maildev/maildev
    ports:
     - 1080:1080
     - 1025:1025
  storage:
    image: minio/minio
    restart: always
    environment: 
        - MINIO_ACCESS_KEY=mmmm12345
        - MINIO_SECRET_KEY=xxxx12345
    volumes: 
        - storage:/storage
    command: server /storage --console-address ":9001"
    ports:
        - 9060:9000
        - 9061:9001
  rabbit:
      image: rabbitmq:3.8.17-management-alpine
      environment: 
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=1234c56
          - RABBITMQ_DEFAULT_VHOST=localhost
      ports:
          - 5672:5672
          - 8082:15672
      volumes:
          - rabbit-data:/var/lib/rabbitmq
volumes:
    rabbit-data: {}
    storage: {}